---
apiVersion: v1
kind: Service
metadata:
  name: netstatd-headless
  namespace: kube-system
  labels:
    app: netstatd
spec:
  clusterIP: None
  selector:
    app: netstatd
  ports:
    - name: http
      port: 5280
      targetPort: 5280
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: netstatd
  namespace: kube-system
  labels:
    app: netstatd
spec:
  type: ClusterIP
  selector:
    app: netstatd
  ports:
    - name: http-single
      port: 5280
      targetPort: 5280
      protocol: TCP
    - name: http-mux
      port: 6280
      targetPort: 6280
      protocol: TCP
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netstatd
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: netstatd
  template:
    metadata:
      labels:
        app: netstatd
    spec:
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
        - name: zot
      containers:
        - name: netstatd
          image: git.codemowers.io/laurivosandi/netstatd
          args:
            - "--log-level=warn"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 5280
              protocol: TCP
              name: http
              hostPort: 5280
            - containerPort: 6280
              protocol: TCP
              name: http-mux
              hostPort: 6280
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: FANOUT_SERVICE
              value: netstatd-headless
            - name: LOG_LEVEL
              value: "info"
          securityContext:
            privileged: true
          volumeMounts:
            - name: containerd-sock
              mountPath: /run/containerd/containerd.sock
            - name: sys-kernel-tracing
              mountPath: /sys/kernel/tracing
            - name: sys-kernel-debug
              mountPath: /sys/kernel/debug
      volumes:
        - name: containerd-sock
          hostPath:
            path: /run/k3s/containerd/containerd.sock
            type: Socket
        - name: sys-kernel-tracing
          hostPath:
            path: /sys/kernel/tracing
            type: Directory
        - name: sys-kernel-debug
          hostPath:
            path: /sys/kernel/debug
            type: Directory
      tolerations:
        - effect: NoSchedule
          operator: Exists
      serviceAccountName: netstatd
      nodeSelector:
        kubernetes.io/arch: amd64
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: netstatd
  namespace: kube-system
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: netstatd
  namespace: kube-system
  labels:
    app: netstatd
spec:
  selector:
    matchLabels:
      app: netstatd
  namespaceSelector:
    matchNames:
      - kube-system
  podMetricsEndpoints:
    - port: http
