// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"

	"github.com/cilium/ebpf"
)

type tracerConnEvent struct {
	Pid        uint32
	Pad        uint32
	Family     uint16
	Sport      uint16
	Dport      uint16
	State      uint32
	Protocol   uint8
	EventType  uint8
	SockCookie uint64
	Ipv4       struct {
		Saddr uint32
		Daddr uint32
	}
	Ipv6 struct {
		Saddr [16]uint8
		Daddr [16]uint8
	}
}

// loadTracer returns the embedded CollectionSpec for tracer.
func loadTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tracer: %w", err)
	}

	return spec, nil
}

// loadTracerObjects loads tracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tracerObjects
//	*tracerPrograms
//	*tracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerSpecs struct {
	tracerProgramSpecs
	tracerMapSpecs
}

// tracerSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerProgramSpecs struct {
	TraceInetSockSetState *ebpf.ProgramSpec `ebpf:"trace_inet_sock_set_state"`
	TraceInetCskAcceptRet *ebpf.ProgramSpec `ebpf:"trace_inet_csk_accept_ret"`
	TraceSysExitListen    *ebpf.ProgramSpec `ebpf:"trace_sys_exit_listen"`
	TraceUdpRecvmsg       *ebpf.ProgramSpec `ebpf:"trace_udp_recvmsg"`
	TraceUdpSendmsg       *ebpf.ProgramSpec `ebpf:"trace_udp_sendmsg"`
}

// tracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerMapSpecs struct {
	Config *ebpf.MapSpec `ebpf:"config"`
	Events *ebpf.MapSpec `ebpf:"events"`
}

// tracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerObjects struct {
	tracerPrograms
	tracerMaps
}

// tracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerPrograms struct {
	TraceInetSockSetState *ebpf.Program `ebpf:"trace_inet_sock_set_state"`
	TraceInetCskAcceptRet *ebpf.Program `ebpf:"trace_inet_csk_accept_ret"`
	TraceSysExitListen    *ebpf.Program `ebpf:"trace_sys_exit_listen"`
	TraceUdpRecvmsg       *ebpf.Program `ebpf:"trace_udp_recvmsg"`
	TraceUdpSendmsg       *ebpf.Program `ebpf:"trace_udp_sendmsg"`
}

// tracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerMaps struct {
	Config *ebpf.Map `ebpf:"config"`
	Events *ebpf.Map `ebpf:"events"`
}

func (t *tracerObjects) Close() error {
	var err error
	if e := t.tracerPrograms.Close(); e != nil {
		err = e
	}
	if e := t.tracerMaps.Close(); e != nil {
		err = e
	}
	return err
}

func (t *tracerPrograms) Close() error {
	var err error
	if e := t.TraceInetSockSetState.Close(); e != nil {
		err = e
	}
	if e := t.TraceInetCskAcceptRet.Close(); e != nil {
		err = e
	}
	if e := t.TraceSysExitListen.Close(); e != nil {
		err = e
	}
	if e := t.TraceUdpRecvmsg.Close(); e != nil {
		err = e
	}
	if e := t.TraceUdpSendmsg.Close(); e != nil {
		err = e
	}
	return err
}

func (t *tracerMaps) Close() error {
	var err error
	if e := t.Config.Close(); e != nil {
		err = e
	}
	if e := t.Events.Close(); e != nil {
		err = e
	}
	return err
}

// Do not access this directly.
//
//go:embed tracer_bpfel.o
var _TracerBytes []byte
